### ISSUE TITLE
Doesn't seem to work 

### ISSUE THREAD

**Issue by sick13** [adrianvanderwal/Burner-Leech#4]
i put too furnaces two burner inserters and they wont leech also tried with electric inserters.
the burner inserters wont fuel them selves nor transfer fuel to other entities that require fuel

P.S
also in the info.json you have put 0.17.69 as dependency,thus the mod get's disabled

**Comment by adrianvanderwal** [comment]
1. What version of the mod are you using?

2. The minimum version of base required in the latest version is correct. It is incompatible with any version of base with a lower version number. It's waiting on release of 0.17.69 which include a new C++ version of the leeching features.

**Comment by sick13** [comment]
0.17.68,so basically it will work with ....69?
